import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import Sidebar from "@/src/Components/layout/Sidebar"
import Navbar from "@/src/Components/layout/Navbar"
import { getCookie } from "../serverActions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser: any = await getCookie("currentUser")
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        {currentUser?.accessToken && <Navbar />}
        <div className="flex items-start">
          {currentUser?.accessToken &&
            <Sidebar />
          }
          <div className="min-h-screen w-full p-2">
            {children}
            {/* {currentUser?.accessToken && <Footer />} */}
          </div>
        </div>

      </body>
    </html>
  );
}
